### ISSUE TITLE
[BUG] Duplicate data values in the Select Component when data is defined using calculated option

### ISSUE THREAD

**Issue by giovanidalpiva** [formio/react-formio#210]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version:4.0.0-beta.53
- Frontend framework: 4.0.0-beta.33
- Browser: Google Chrome
- Browser version: 74.0.3729.169 (Official Build) (64-bit)

## Steps to Reproduce
1. create a new form
2. add a select component
3. configure the data as calculated value and add a JSONLogic as follows (which is configured related with another select component, where the data was add without any special logic):

```
{
  "if": [
    {
      "===": [
        {
          "var": "data.tipoDePessoa"
        },
        "pessoaFisica"
      ]
    },
    [
      {
        "label": "Urbano",
        "value": "urbano"
      }
    ],
    {
      "===": [
        {
          "var": "data.tipoDePessoa"
        },
        "pessoaJuridica"
      ]
    },
    [
      {
        "label": "MEI",
        "value": "mei"
      }
    ],
    []
  ]
}
```

## Expected behavior
Was expected to see in the screen just one register in the select according to user's choice in the previous field

## Observed behavior
The data is duplicating in the select

## Example

![Screen Shot 2019-06-25 at 10 47 20 PM](https://user-images.githubusercontent.com/2424751/60145178-9f4f2500-979b-11e9-8aa7-14ecd766e9a2.png)

I tried also to configure by javascript, but the behavior was the same: duplicated items in the screen

**Comment by randallknutson** [comment]
Looks like a bug. Are you able to debug it and do a pull request? We can add it to our backlog to get fixed when we have a chance to look at it.

**Comment by giovanidalpiva** [comment]
ok, tested in this version and this bug is ok, but there is a new issue now with the wizard that did not happen before. Open the issue #215

**Comment by giovanidalpiva** [comment]
sorry, closed the wrong issue

**Comment by jhen1422** [comment]
This should be resolved in version 4.4.2

**Comment by syed-farjana** [comment]
I think issue is not resolved yet even in 4.4.2 also.  I am using 4.12.0 version the issue remains same and I have directly tested this issue portal.formio

**Comment by wag110894** [comment]
@syed-farjana can you provide a form to where you can replicate this issue on our side?
