### ISSUE TITLE
Uncaught TypeError: Cannot read property 'routerContext' of undefined

### ISSUE THREAD

**Issue by Sineliad** [formio/react-formio#77]
Hi :) ,

I got that error when I installed react-formio:
"Uncaught TypeError: Cannot read property 'routerContext' of undefined" 
The error is in webpack:///./~/redux-view/lib/ReduxView.js

My package.json dependencies are: 
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-formio": "^0.10.11",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.6",
    "redux": "^3.6.0"
  }

And node version is v6.4.0

Thanks

**Comment by randallknutson** [comment]
This was an old version of redux-view that we were using. I just released v0.11.0 to fix this. Please try it out.

**Comment by Sineliad** [comment]
Thanks @randallknutson  - but still having the same issue

this is a new react-create-app folder with only react-formio .
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import {Formio} from 'react-formio';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>TESTING FORMIO</h2>
        </div>
        <p className="App-intro">
            <Formio src="https://example.form.io/example" />
        </p>
      </div>
    );
  }
}

export default App;

```  

And this is the package.json
```
{
  "name": "formio",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.7.0"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-formio": "^0.11.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.6",
    "redux": "^3.6.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```
